spring:
  cloud:
    nacos:
      server-addr: @nacos.addr@
      password: @nacos.password@
      username: @nacos.username@
      discovery:
        namespace: @nacos.service.namespace@
        group: @nacos.service.group@
      config:
        import-check:
          enabled: false
        namespace: @nacos.service.namespace@
        group: @nacos.service.group@
  config:
    import:
      - nacos:kiwi-gateway-intercept.yml
      - nacos:kiwi-gateway-redis.yml
      - nacos:kiwi-redis-session.yml
      - nacos:kiwi-cookie-path.yml